apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: docker-jenkins-test
spec:
  template:
    metadata:
      labels:
        app: docker-jenkins-test
    spec:
      containers:
      - name: docker-jenkins-test
        image: hyperion.azurecr.io/docker_jenkins_test
